aiart_auth/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.views import LogoutView

app_name = "auth"
urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name="register"),
    path('profile/<uuid:uuid>', views.ProfileView.as_view(), name="profile"),
    path('profile/', views.ProfileView.as_view(), name="profile"),
    path('profile/edit/',views.ProfileEditView.as_view(), name="profile_edit"),
    path('profile/password/', views.PasswordChange.as_view(), name='password_change')
] 

htmxpatterns = [
   path('follow',views.follow,name="follow"),
]

urlpatterns += htmxpatterns

aiart_main/urls.py
from django.urls import path

from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('help/', views.help, name='help'),
    path('contact/', views.contact, name='contact'),
    path('report/', views.report, name='report'),
]

aiartsharing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('content/', include('aiart_content.urls')),
    path('auth/', include('aiart_auth.urls')),
    path('', include('aiart_main.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aiart_main/models.py
from django.db import models
from aiart_auth.models import CustomUser
from aiart_content.models import ImagePost
from django.utils import timezone
import uuid
# Create your models here.


class Report(models.Model):

    report_choices = [
    ("report_broken_url", "I can't view the image for this post."),
    ("report_not_aiart", "This post is not AI Art."),
    ("report_harassment", "This post is targetted harassment."),
    ("report_selfharm", "This post is promoting suicide or self-harm."),
    ("report_spam", "This post is spam."),
    ("report_untagged_sexual_content", "This post is not tagged for sexual content (18+)."),
    ("report_sexual_content_minors", "This post contains sexual content involving minors."),
    ("report_other", "Other (please use the box below)"),
    ]

    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE) 
    report_date = models.DateTimeField(default=timezone.now, editable=False)
    report_option = models.CharField(max_length=300, choices=report_choices)
    other_option = models.TextField()

class ImagePostReport(Report):
    imagepost = models.ForeignKey(ImagePost, on_delete=models.CASCADE, editable=False)

aiart_main/forms.py
from django import forms
from .models import ImagePostReport
class ImagePostReportForm(forms.ModelForm):

    class Meta:
        model = ImagePostReport
        fields = ("report_option","other_option",)
        labels = {
            "report_option":'Please select an option',
            "other_option":"Explain why you're reporting this post",
        }

aiart_main/views.py
from django.shortcuts import render, HttpResponse
from django.urls import reverse
from aiart_content.forms import SimpleSearchForm, AdvancedLocalSearchForm, AdvancedOnlineServiceSearchForm
from aiart_content.models import ImagePost
from .models import ImagePostReport
# Create your views here.

def index(request):
    simpleform = SimpleSearchForm
    advanced_local_form = AdvancedLocalSearchForm
    advanced_online_form = AdvancedOnlineServiceSearchForm
    totalPosts = ImagePost.objects.count()
    context = {'simpleform':simpleform, 'advanced_local_form':advanced_local_form, 'advanced_online_form': advanced_online_form, 'totalPosts':totalPosts}
    return render(request, template_name='index.html', context=context)

def about(request):
    return render(request, template_name='about.html')

def help(request):
    return render(request, template_name='help.html')

def contact(request):
    return render(request, template_name='contact.html')


#HTMX Views
def report(request):
    if (request.method=='POST'):
        report_option = request.POST['report_option']
        other_option = request.POST['other_option']
        imagepost = ImagePost.objects.get(uuid=request.POST['post_uuid'])
        report = ImagePostReport.objects.create(report_option=report_option,other_option=other_option,user=request.user, imagepost=imagepost)
        report.save()
        return HttpResponse("Report Successful")

aiart_main/templates/about.html
{% extends 'base.html' %}
{% block content %}
<div class="content">
<h1> What is AI Art Sharing? </h1>
<p>AI Art Sharing is a platform where you can search, upload and discuss AI image generation. Our goal is to provide a free-form upload of images made by AI that you can use to share images with the world.</p>
<p> We want this platform to be a social hub for sharing images for the end user to get inspiration from, and we are always looking for ways to empower your generation capabilities through a powerful search engine.</p>

<h1> The necessity </h1>
<p> AI Art requires you to give it a prompt, a sentence or collection of words that describe what you want the output image to be. Sometimes you don't know which words make up a specific style, so you can check out the details 
    of the image to figure it out. Plus, since we categorize images from any service, you can use whatever active subscription you have or figure out which service best suits your needs!
</p>

<h1> Resources </h1>
<p> We recommend you visit these resources to get started with image generation, then comeback and share your results! </p>

<ul>
    <li> <a href="https://github.com/AUTOMATIC1111/stable-diffusion-webui"> Stable Diffusion Web UI</a> </li>
    <ul>
        <li><a href="https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Install-and-Run-on-NVidia-GPUs"> Installation (Nvidia)</a>  </li>
        <li><a href="https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Install-and-Run-on-AMD-GPUs"> Installation (AMD)</a>  </li>
        <li><a href="https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Installation-on-Apple-Silicon"> Installation (Apple's M1 and M2 CPUs)</a>  </li>
        <li><a href="https://rentry.org/voldyold"> Voldy GUI Guide</a>  </li>
    </ul>
    <li> <a href="https://www.midjourney.com/home/"> Midjourney</a> </li>
    <li> <a href="https://playgroundai.com/"> PlaygroundAI</a> </li>
    <li> <a href="https://openai.com/product/dall-e-2"> DALL-E 2</a> </li>
    <li> <a href="https://novelai.net/"> NovelAI </a> </li>
    <li> <a href="https://creator.nightcafe.studio/studio"> NightCafe </a> </li>
</ul>
</div>
{% endblock content %}

aiart_main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI Art Sharing</title>

    <!-- Bulma -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <!-- Custom CSS -->
    <link rel="stylesheet" href={% static 'css/base.css' %}/>
    <!-- HTMX and HyperScript-->
    <script src="https://unpkg.com/htmx.org@1.8.6" integrity="sha384-Bj8qm/6B+71E6FQSySofJOUjA/gq330vEqjFx9LakWybUySyI1IQHwPtbTU7bNwx" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/hyperscript.org@0.9.8"></script>
</head>
<body>
    {% include 'partials/navbar.html' %}
    <div class='container is-fluid p-4 fit-screen'>
        {% block content %}
        {% endblock %}
    </div>
    {% include 'partials/footer.html' %}

    <script>
        
        document.body.addEventListener('htmx:configRequest', (event) => {
            event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
        })

    </script>
</body>
</html>

aiart_main/templates/contact.html
{% extends 'base.html' %}
{% block content %}
<div class="content">
    <h1> Contact us </h1>
    <p>If you need to contact us directly, please email <a> bernardo.ribeiro.work@gmail.com </a></p>
    <p>For code related problems and issues, as well as suggestions to improve the platform, please reach out to us at <a href="https://github.com/bernasx/aiartsharing"> https://github.com/bernasx/aiartsharing</a></p>

    <h1> Content related issues </h1>
    <p>To report any content abuse please use our report system. We will try to deal with any abusive or offensive content as soon as possible.</p>

    <h1> Social Media </h1>
    You can get updates from us directly if you follow us on <a href="">Twitter</a> or by joining our <a href="">Discord Server</a>.
</div>
{% endblock content %}

aiart_main/templates/help.html
{% extends 'base.html' %}
{% block content %}
<div class="content">
    <h1> How do I search images? </h1>
    <p> You can search images by heading over to the homepage or the posts section. You can search for a term in a simple manner using the <u> Simple Search </u> or use the 
    <u> Advanced Search </u> to filter posts down to exactly what you need.
    </p>

    <h1> Online Service and Local Generation </h1>
    <p> By default, the website lets you upload and search for images in a way that fits locally generated images with a lot of options, like the ones generated in <a href="https://github.com/AUTOMATIC1111/stable-diffusion-webui"> Stable Diffusion's Web UI by AUTOMATIC1111.</a></p>
    <p> While this works great, some online services like <a href="https://www.midjourney.com/home/"> Midjourney </a> are a lot simpler, 
        and fit everything in their prompts. For this reason, those services can be searched by checking the <u> online service</u> checkbox.</p>

    <h1> Search fields </h1>

    <ul>
        <li><strong> Prompt / Search Term: </strong> </li> This parameter searches prompts and is generally what you want to use to search for what you have in mind (<em>e.g: dog, car, river</em>). 
    </ul>

    <ul>
        <li><strong> Model: </strong> </li> This parameter lets you search for a specific model. It is only used when searching for locally generated images likes ones generated in the Stable Diffusion Web UI. 
    </ul>

    <ul>
        <li><strong> Keywords: </strong> </li> Keywords search metadata fields like <u>notes</u> and <u>generation details</u>. This is useful to look for images that use a particular sampling method or
        any other attribute or word that would show up in those fields.
    </ul>

    <ul>
        <li><strong> Service: </strong> </li> Lets you choose between many different online services that are used to generated AI art.
    </ul>
</div>
{% endblock content %}

aiart_main/templates/index.html
{% extends 'base.html' %}

{% block content %}
<section class="section">
    <div class="content has-text-centered">
        <h3 class="is-size-2">
            Welcome to the web's #1 AI art and image repository
        </h3>
        <p class="is-size-4">
            Here you can find and upload all manner of AI generated images
        </p>
        <br>
        <div class="container">
            <p class="is-size-6">
                We are currently archiving <strong>{{totalPosts}}</strong> images and counting!
            </p>
            <p class="is-size-6">
                Use the search below to find the perfect image prompts and models you can use in your own creations.
            </p>
            {% if not user.is_authenticated %}
            <p class="is-size-6">
                <a href="{% url 'auth:register' %}" class="">Create a new account</a> to like, comment and favorite
                images!
            </p>
        </div>

        {% endif %}
    </div>

    <div class="container has-text-centered mt-4">
        <a id="discord-button" class="button" href="">
            <span class=""> Discord</span>
            <span class="icon social-media-icon">
                <!-- Uploaded to: SVG Repo, www.svgrepo.com, Transformed by: SVG Repo Mixer Tools -->
                <svg width="24px" height="24px" viewBox="0 -28.5 256 256" version="1.1"
                    xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                    preserveAspectRatio="xMidYMid" fill="#000000">

                    <g id="SVGRepo_bgCarrier" stroke-width="0" />

                    <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round" />

                    <g id="SVGRepo_iconCarrier">
                        <g>
                            <path
                                d="M216.856339,16.5966031 C200.285002,8.84328665 182.566144,3.2084988 164.041564,0 C161.766523,4.11318106 159.108624,9.64549908 157.276099,14.0464379 C137.583995,11.0849896 118.072967,11.0849896 98.7430163,14.0464379 C96.9108417,9.64549908 94.1925838,4.11318106 91.8971895,0 C73.3526068,3.2084988 55.6133949,8.86399117 39.0420583,16.6376612 C5.61752293,67.146514 -3.4433191,116.400813 1.08711069,164.955721 C23.2560196,181.510915 44.7403634,191.567697 65.8621325,198.148576 C71.0772151,190.971126 75.7283628,183.341335 79.7352139,175.300261 C72.104019,172.400575 64.7949724,168.822202 57.8887866,164.667963 C59.7209612,163.310589 61.5131304,161.891452 63.2445898,160.431257 C105.36741,180.133187 151.134928,180.133187 192.754523,160.431257 C194.506336,161.891452 196.298154,163.310589 198.110326,164.667963 C191.183787,168.842556 183.854737,172.420929 176.223542,175.320965 C180.230393,183.341335 184.861538,190.991831 190.096624,198.16893 C211.238746,191.588051 232.743023,181.531619 254.911949,164.955721 C260.227747,108.668201 245.831087,59.8662432 216.856339,16.5966031 Z M85.4738752,135.09489 C72.8290281,135.09489 62.4592217,123.290155 62.4592217,108.914901 C62.4592217,94.5396472 72.607595,82.7145587 85.4738752,82.7145587 C98.3405064,82.7145587 108.709962,94.5189427 108.488529,108.914901 C108.508531,123.290155 98.3405064,135.09489 85.4738752,135.09489 Z M170.525237,135.09489 C157.88039,135.09489 147.510584,123.290155 147.510584,108.914901 C147.510584,94.5396472 157.658606,82.7145587 170.525237,82.7145587 C183.391518,82.7145587 193.761324,94.5189427 193.539891,108.914901 C193.539891,123.290155 183.391518,135.09489 170.525237,135.09489 Z"
                                fill="#ffffff" fill-rule="nonzero"> </path>
                        </g>
                    </g>

                </svg>
            </span>

        </a>
        <a id="twitter-button" class="button" href="">
            <span class=""> Twitter </span>

            <span class="icon social-media-icon">
                <svg viewBox="0 -2 20 20" version="1.1" xmlns="http://www.w3.org/2000/svg"
                    xmlns:xlink="http://www.w3.org/1999/xlink" fill="#000000">
                    <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                    <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                    <g id="SVGRepo_iconCarrier">
                        <title>twitter [#154]</title>
                        <desc>Created with Sketch.</desc>
                        <defs> </defs>
                        <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                            <g id="Dribbble-Light-Preview" transform="translate(-60.000000, -7521.000000)" fill="#FFF">
                                <g id="icons" transform="translate(56.000000, 160.000000)">
                                    <path
                                        d="M10.29,7377 C17.837,7377 21.965,7370.84365 21.965,7365.50546 C21.965,7365.33021 21.965,7365.15595 21.953,7364.98267 C22.756,7364.41163 23.449,7363.70276 24,7362.8915 C23.252,7363.21837 22.457,7363.433 21.644,7363.52751 C22.5,7363.02244 23.141,7362.2289 23.448,7361.2926 C22.642,7361.76321 21.761,7362.095 20.842,7362.27321 C19.288,7360.64674 16.689,7360.56798 15.036,7362.09796 C13.971,7363.08447 13.518,7364.55538 13.849,7365.95835 C10.55,7365.79492 7.476,7364.261 5.392,7361.73762 C4.303,7363.58363 4.86,7365.94457 6.663,7367.12996 C6.01,7367.11125 5.371,7366.93797 4.8,7366.62489 L4.8,7366.67608 C4.801,7368.5989 6.178,7370.2549 8.092,7370.63591 C7.488,7370.79836 6.854,7370.82199 6.24,7370.70483 C6.777,7372.35099 8.318,7373.47829 10.073,7373.51078 C8.62,7374.63513 6.825,7375.24554 4.977,7375.24358 C4.651,7375.24259 4.325,7375.22388 4,7375.18549 C5.877,7376.37088 8.06,7377 10.29,7376.99705"
                                        id="twitter-[#154]"> </path>
                                </g>
                            </g>
                        </g>
                    </g>
                </svg>
            </span>
        </a>

        <a id="github-button" class="button" href="">
            <span class=""> GitHub </span>
            <span class="icon social-media-icon">
                <svg viewBox="0 0 20 20" version="1.1" xmlns="http://www.w3.org/2000/svg"
                    xmlns:xlink="http://www.w3.org/1999/xlink" fill="#000000">
                    <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                    <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                    <g id="SVGRepo_iconCarrier">
                        <title>github [#142]</title>
                        <desc>Created with Sketch.</desc>
                        <defs> </defs>
                        <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                            <g id="Dribbble-Light-Preview" transform="translate(-140.000000, -7559.000000)" fill="#FFF">
                                <g id="icons" transform="translate(56.000000, 160.000000)">
                                    <path
                                        d="M94,7399 C99.523,7399 104,7403.59 104,7409.253 C104,7413.782 101.138,7417.624 97.167,7418.981 C96.66,7419.082 96.48,7418.762 96.48,7418.489 C96.48,7418.151 96.492,7417.047 96.492,7415.675 C96.492,7414.719 96.172,7414.095 95.813,7413.777 C98.04,7413.523 100.38,7412.656 100.38,7408.718 C100.38,7407.598 99.992,7406.684 99.35,7405.966 C99.454,7405.707 99.797,7404.664 99.252,7403.252 C99.252,7403.252 98.414,7402.977 96.505,7404.303 C95.706,7404.076 94.85,7403.962 94,7403.958 C93.15,7403.962 92.295,7404.076 91.497,7404.303 C89.586,7402.977 88.746,7403.252 88.746,7403.252 C88.203,7404.664 88.546,7405.707 88.649,7405.966 C88.01,7406.684 87.619,7407.598 87.619,7408.718 C87.619,7412.646 89.954,7413.526 92.175,7413.785 C91.889,7414.041 91.63,7414.493 91.54,7415.156 C90.97,7415.418 89.522,7415.871 88.63,7414.304 C88.63,7414.304 88.101,7413.319 87.097,7413.247 C87.097,7413.247 86.122,7413.234 87.029,7413.87 C87.029,7413.87 87.684,7414.185 88.139,7415.37 C88.139,7415.37 88.726,7417.2 91.508,7416.58 C91.513,7417.437 91.522,7418.245 91.522,7418.489 C91.522,7418.76 91.338,7419.077 90.839,7418.982 C86.865,7417.627 84,7413.783 84,7409.253 C84,7403.59 88.478,7399 94,7399"
                                        id="github-[#142]"> </path>
                                </g>
                            </g>
                        </g>
                    </g>
                </svg>
            </span>
        </a>
    </div>
</section>
{%include 'search/search.html' %}

{% endblock content %}

aiart_main/templates/report.html
{%load widget_tweaks%}
<div id="report-modal" class="modal">
    <div class="modal-background" _="on click toggle .is-active on #report-modal"></div>
    <div class="modal-card">
      <header class="modal-card-head">
        <p class="modal-card-title">Report this post</p>
        <button class="delete" aria-label="close" _="on click toggle .is-active on #report-modal"></button>
      </header>
    <form method="POST" hx-post="{% url 'main:report' %}" hx-swap="none" autocomplete='off'>
    {% csrf_token %}
    <input type="hidden" name="post_uuid" value="{{object.uuid}}">
      <section class="modal-card-body">

        <div class="field">
            <label class="label">{{ report_form.report_option.label_tag }}</label>
            {{ report_form.report_option.errors }}
            <div class="control">
                <div class="select">
                    {% render_field report_form.report_option%}
                </div>
            </div>
        </div>

        <div class="field">
            <label class="label">{{ report_form.other_option.label_tag }}</label>
            {{ report_form.other_option.errors }}

            <div class="control">
                {% render_field report_form.other_option class="textarea"%}
            </div>
        </div>

      </section>
      <footer class="modal-card-foot">
        <button type="submit" class="button is-primary" _="on click toggle .is-active on #report-modal then toggle .is-hidden on #notification">Report</button>
        <button type="button" class="button" _="on click toggle .is-active on #report-modal">Cancel</button>
      </footer>

    </form>
    </div>
</div>