aiart_auth/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.views import LogoutView

app_name = "auth"
urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name="register"),
    path('profile/<uuid:uuid>', views.ProfileView.as_view(), name="profile"),
    path('profile/', views.ProfileView.as_view(), name="profile"),
    path('profile/edit/',views.ProfileEditView.as_view(), name="profile_edit"),
    path('profile/password/', views.PasswordChange.as_view(), name='password_change')
] 

htmxpatterns = [
   path('follow',views.follow,name="follow"),
]

urlpatterns += htmxpatterns

aiart_content/urls.py
from django.urls import path
from . import views

app_name = 'content'
urlpatterns = [
   path('create/',views.CreateImagePostView, name='create_imagepost'),
   path('detail/<uuid:uuid>', views.DetailImagePostView.as_view(), name='detail_imagepost'),
   path('posts/',views.ListImagePostsView.as_view(), name='list_imagepost'),
   path('followingfeed/',views.ListImagePostsFollowingFeed.as_view(), name='following_feed'),
   path('favorites/',views.ListImagePostsFavorites.as_view(), name='favorites')
]

htmx_urlpatterns = [
   path('like_imagepost/', views.likeImagePost, name="like_imagepost"),
   path('favorite_imagepost/', views.favoriteImagePost, name="favorite_imagepost"),
   path('search/',views.searchView, name='search'),
   path('post_comment',views.postComment,name="post_comment")
]


urlpatterns += htmx_urlpatterns

aiartsharing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('content/', include('aiart_content.urls')),
    path('auth/', include('aiart_auth.urls')),
    path('', include('aiart_main.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aiart_content/forms.py
from django import forms
from .models import ImagePost, ImagePostComment

class ImagePostLocalCreationForm(forms.ModelForm):

    post_type = forms.CharField(widget=forms.HiddenInput, initial='local')

    class Meta:
        model = ImagePost
        fields = ("image_url","model",
                  "hypernetwork","positive_prompt","negative_prompt",
                  "notes","generation_details","isOnlineService","onlineService")
        labels = {
            "image_url":'Image URL',
            "model":"Model",
            "hypernetwork": "Hypernetwork",
            "positive_promopt":"Positive Prompt",
            "negative_prompt":"Negative Prompt",
            "notes":"Notes",
            "generation_details": "Generation Details",
        }

class ImagePostOnlineCreationForm(forms.ModelForm):

    post_type = forms.CharField(widget=forms.HiddenInput, initial='online')

    class Meta:
        model = ImagePost
        fields = ("image_url","model",
                  "hypernetwork","positive_prompt","negative_prompt",
                  "notes","generation_details","isOnlineService","onlineService")
        labels = {
            "image_url":'Image URL',
            "model":"Model",
            "hypernetwork": "Hypernetwork",
            "positive_promopt":"Positive Prompt",
            "negative_prompt":"Negative Prompt",
            "notes":"Notes",
            "generation_details": "Generation Details",
            "onlineService": "Online Service"
        }


    def clean(self):
        cd = super(ImagePostOnlineCreationForm, self).clean()

        onlineService = cd.get("onlineService")
        if onlineService == "":
            self.add_error('onlineService', forms.ValidationError('Please select a service!'))     
        return cd
        

class ImagePostChangeForm(forms.ModelForm):

    class Meta:
        model = ImagePost
        fields = ("image_url","model",
                  "hypernetwork","positive_prompt","negative_prompt",
                  "notes","generation_details","onlineService")
        labels = {
            "image_url":'Image URL',
            "model":"Model",
            "hypernetwork": "Hypernetwork",
            "positive_promopt":"Positive Prompt",
            "negative_prompt":"Negative Prompt",
            "notes":"Notes",
            "generation_details": "Generation Details",
            "isOnlineService": "Generated in an Online Service?",
            "onlineService": "Online Service"
        }

#Search

class SimpleSearchForm(forms.Form):
    keyword = forms.CharField(label="Search for anything", max_length=100, required=False)
    search_type = forms.CharField(widget=forms.HiddenInput, initial='simple')
    
    sort_options = [('recent','Recent'),('popular','Popularity'),('views','Views')]
    sort_by = forms.ChoiceField(label="Sort by", choices=sort_options)

class AdvancedLocalSearchForm(forms.Form):
    prompt = forms.CharField(label="Prompt / Search Term", max_length=100, required=False)
    model = forms.CharField(label="Model", max_length=100, required=False)
    keyword = forms.CharField(label="Keywords", max_length=100, required=False)
    search_type = forms.CharField(widget=forms.HiddenInput, initial='advanced_local')

    sort_options = [('recent','Recent'),('popular','Popularity'),('views','Views')]
    sort_by = forms.ChoiceField(label="Sort by", choices=sort_options)

class AdvancedOnlineServiceSearchForm(forms.Form):
    DALL_E = 'DALL-E'
    NOVEL_AI = 'Novel AI'
    MIDJOURNEY = 'Midjourney'

    choices = [('','---------'),(DALL_E,'DALL-E 2'),(NOVEL_AI,'Novel AI'),(MIDJOURNEY,'Midjourney')]

    prompt = forms.CharField(label="Prompt / Search Term", max_length=100, required=False)
    service = forms.ChoiceField(label="Service", choices=choices, required=False)
    keyword = forms.CharField(label="Keywords", max_length=100, required=False)
    search_type = forms.CharField(widget=forms.HiddenInput, initial='advanced_online')

    sort_options = [('recent','Recent'),('popular','Popularity'),('views','Views')]
    sort_by = forms.ChoiceField(label="Sort by", choices=sort_options)

# Comment

class CommentCreationForm(forms.ModelForm):

    class Meta:
        model = ImagePostComment

        fields = ("content",)
        labels = {
            "content":"Comment on this image!",
        }

aiart_content/views.py
from django.views.generic import DetailView, ListView
from .forms import ImagePostLocalCreationForm, ImagePostOnlineCreationForm, SimpleSearchForm, AdvancedLocalSearchForm, AdvancedOnlineServiceSearchForm, CommentCreationForm
from aiart_main.forms import ImagePostReportForm
from .models import ImagePost, ImagePostComment
from django.shortcuts import render, redirect, HttpResponse
from aiart_auth.models import CustomUser, Followers
from django.urls import reverse
from django.db.models import Q
from django.db.models import Count
# Create your views here.

def CreateImagePostView(request):
    if(request.method == 'GET'):
        local_form = ImagePostLocalCreationForm
        online_form = ImagePostOnlineCreationForm
        context = {'local_form':local_form, 'online_form':online_form}
        return render(request,'imageposts/create.html', context)
    if(request.method =='POST'):
        context = {}
        if(request.POST['post_type'] == 'local'):
            local_form = ImagePostLocalCreationForm(request.POST, request.FILES)
            online_form = ImagePostOnlineCreationForm
            context = {'local_form':local_form, 'online_form':online_form}
            if local_form.is_valid():
                imagepost = ImagePost(
                    user = request.user,
                    image_url = request.POST['image_url'],
                    positive_prompt = request.POST['positive_prompt'],
                    notes = request.POST['notes'],
                    generation_details = request.POST['generation_details'],
                    model = request.POST['model'],
                    hypernetwork = request.POST['hypernetwork'],
                    negative_prompt = request.POST['negative_prompt'],
                    isOnlineService = False,
                )
                imagepost.save()
                return redirect('content:detail_imagepost',uuid=imagepost.uuid)
            else:
                context['onlineServiceReload'] = False
                return render(request,'imageposts/create.html', context)
        else: 
            local_form = ImagePostLocalCreationForm
            online_form = ImagePostOnlineCreationForm(request.POST, request.FILES)
            context = {'local_form':local_form, 'online_form':online_form}
            if online_form.is_valid():
                imagepost = ImagePost (
                    user = request.user,
                    image_url = request.POST['image_url'],
                    positive_prompt = request.POST['positive_prompt'],
                    notes = request.POST['notes'],
                    generation_details = request.POST['generation_details'],
                    negative_prompt = request.POST['negative_prompt'],
                    onlineService = request.POST['onlineService'],
                    isOnlineService = True,
                )

                if request.POST['model'] != '':
                    imagepost.model = request.POST['model']
                else:
                    imagepost.model = imagepost.onlineService

                imagepost.save()
                return redirect('content:detail_imagepost',uuid=imagepost.uuid)
            else:
                context['onlineServiceReload'] = True
                return render(request,'imageposts/create.html', context)


class DetailImagePostView(DetailView):
    model = ImagePost
    template_name = 'imageposts/detail.html'


    def get_object(self):
        post = ImagePost.objects.get(uuid=self.kwargs.get('uuid'))
        post.views += 1
        post.save()
        return post
    
    def get_context_data(self, **kwargs):
         # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        post = ImagePost.objects.get(uuid=self.kwargs.get('uuid'))
        # We have to separate these from the rest of the page so HTMX can rewrite them and preserve stuff in the template
        context['imagepost_uuid'] = post.uuid
        if self.request.user.is_authenticated:
            context['user_liking_uuid'] = self.request.user.uuid
        context['likes'] = post.liked_image_posts.all().count()
        context['report_form'] = ImagePostReportForm

        # gets random posts to be recommended, this is super slow and should be changed eventually
        recommended_posts = ImagePost.objects.all().exclude(uuid=self.kwargs.get('uuid')).order_by('?')[:6]
        context['recommended_posts'] = recommended_posts

        if self.request.user.is_authenticated:
            #Handling likes and Favorites
            if self.request.user.liked_image_posts.filter(uuid=ImagePost.objects.get(uuid=self.kwargs.get('uuid')).uuid).exists():
                # These have to be strings because that's how we get them from the client. Could make them bools but it's just one comparison when rendering the template
                # so it's probably fine.
                context['user_liked_post'] = "True" 


            if self.request.user.favorited_image_posts.filter(uuid=ImagePost.objects.get(uuid=self.kwargs.get('uuid')).uuid).exists():
                context['user_favorited_post'] = "True"

        #comment section
        context['comments'] = ImagePostComment.objects.filter(imagepost=post).order_by('-publish_date')
        form = CommentCreationForm
        context['comment_form'] = form
        return context
    
class ListImagePostsView(ListView):
    model = ImagePost
    template_name = 'imageposts/posts.html'
    paginate_by = 24 

    def get_queryset(self):

        try: 

            # order the posts by whatever
            ordering = ''
            order_query = self.request.GET['sort_by']

            if(order_query == 'recent'):
                ordering = '-publish_date'
            elif(order_query == 'popular'):
                ordering = '-likes'
            elif(order_query == 'views'):
                ordering = '-views'
            else:
                ordering = '-recent'

            # get each a query from each form or type of search individually    
            if (self.request.GET['search_type'] == 'simple'):
                
                keyword = self.request.GET['keyword']
                return ImagePost.objects.filter(
                    Q(positive_prompt__icontains=keyword) | 
                    Q(generation_details__icontains=keyword) | 
                    Q(notes__icontains=keyword) | 
                    Q(model__icontains=keyword)).annotate(likes=Count('liked_image_posts')).order_by(ordering)
            
            elif (self.request.GET['search_type'] == 'advanced_local'):
                prompt = self.request.GET['prompt']
                model = self.request.GET['model']
                keyword = self.request.GET['keyword']
                return ImagePost.objects.filter(Q(isOnlineService=False) & 
                                                Q(positive_prompt__icontains=prompt) & 
                                                Q(model__icontains=model) & 
                                                (Q(generation_details__icontains=keyword) |Q(notes=keyword))).annotate(likes=Count('liked_image_posts')).order_by(ordering)
            
            
            elif (self.request.GET['search_type'] == 'advanced_online'):
                
                prompt = self.request.GET['prompt']
                service = self.request.GET['service']
                keyword = self.request.GET['keyword']
                return ImagePost.objects.filter(Q(isOnlineService=True) 
                                                & Q(positive_prompt__icontains=prompt) 
                                                & Q(onlineService__icontains=service) 
                                                & Q(notes__icontains=keyword)).annotate(likes=Count('liked_image_posts')).order_by(ordering)
            
            
            elif (self.request.GET['search_type'] == 'by_user'):
                
                useruuid = self.request.GET['user_searched']
                user = CustomUser.objects.get(uuid=useruuid)
                return ImagePost.objects.filter(user=user).annotate(likes=Count('liked_image_posts')).order_by(ordering)
            
            else:
                
                return ImagePost.objects.all().annotate(likes=Count('liked_image_posts')).order_by(ordering)
            
        except (KeyError):
        
            return ImagePost.objects.all().annotate(likes=Count('liked_image_posts')).order_by('-publish_date')
        
    def get_context_data(self, **kwargs):
    
        context = super().get_context_data(**kwargs)
        simpleform = SimpleSearchForm
        advanced_local_form = AdvancedLocalSearchForm
        advanced_online_form = AdvancedOnlineServiceSearchForm
        context['simpleform'] = simpleform
        context['advanced_local_form'] = advanced_local_form
        context['advanced_online_form'] = advanced_online_form

        #preserve search parameters, if any
        get_copy = self.request.GET.copy()
        parameters = get_copy.pop('page', True) and get_copy.urlencode()
        context['parameters'] = parameters
        return context

class ListImagePostsFollowingFeed(ListView):
    model = ImagePost
    template_name = 'imageposts/following_feed.html'
    paginate_by = 24 

    def get_queryset(self):
        following_objects = Followers.objects.filter(user_following=self.request.user)
        users = map(lambda x: x.user_being_followed, following_objects)
        return ImagePost.objects.filter(user__in=users).annotate(likes=Count('liked_image_posts')).order_by('-publish_date')
    
    def get_context_data(self, **kwargs):
    
        context = super().get_context_data(**kwargs)

        #preserve search parameters, if any
        get_copy = self.request.GET.copy()
        parameters = get_copy.pop('page', True) and get_copy.urlencode()
        context['parameters'] = parameters
        return context
    

aiart_content/templates/imageposts/partials/detail_like_favorite_buttons.html
<div>
    <button class="button" title="Like" hx-post="{% url 'content:like_imagepost' %}" hx-target='#like-favorite-button-block' hx-swap='innerHTML' hx-vals='{"liked_post":"{{imagepost_uuid}}", "user_liking":"{{user_liking_uuid}}" , "user_did_favorite_post":"{{user_favorited_post}}"}'> 

        {%if user_liked_post == "True" %}
        <svg xmlns="http://www.w3.org/2000/svg" 
        viewBox="-2 -4 24 24" 
        width="24" 
        fill="#BD473F">
        <path d="M9.293 1.55l.707.708.707-.707a5 5 0 1 1 7.071 7.071l-7.07 7.071a1 1 0 0 1-1.415 0L2.222 8.622a5 5 0 1 1 7.07-7.071z"></path>
        </svg> 
        {%else%}
        <svg xmlns="http://www.w3.org/2000/svg" 
        viewBox="-2 -4 24 24" 
        width="24" 
        fill="#BD473F">
        <path d="M3.636 7.208L10 13.572l6.364-6.364a3 3 0 1 0-4.243-4.243L10 5.086l-2.121-2.12a3 3 0 0 0-4.243 4.242zM9.293 1.55l.707.707.707-.707a5 5 0 1 1 7.071 7.071l-7.07 7.071a1 1 0 0 1-1.415 0l-7.071-7.07a5 5 0 1 1 7.07-7.071z"></path>
        </svg> 
        {%endif%}
        

    </button>
    

    <button class="button" title="Favorite" hx-post="{% url 'content:favorite_imagepost' %}" hx-swap='innerHTML' hx-target='#like-favorite-button-block' hx-vals='{"liked_post":"{{imagepost_uuid}}" , "user_liking":"{{user_liking_uuid}}" , "user_did_like_post":"{{user_liked_post}}"}'> 

        {%if user_favorited_post == "True" %}
            <svg xmlns="http://www.w3.org/2000/svg"
            viewBox="-2 -2 24 24"
            width="24"
            fill="#FAD600">
            <path d="M10 16.207l-6.173 3.246 1.179-6.874L.01 7.71l6.902-1.003L10 .453l3.087 6.254 6.902 1.003-4.995 4.869 1.18 6.874z"></path>
            </svg>
        {%else%}
            <svg xmlns="http://www.w3.org/2000/svg" 
            viewBox="-2 -2.5 24 24" 
            width="24" 
            fill="#FAD600">
            <path d="M10 13.554l3.517 1.85-.672-3.917 2.846-2.774-3.932-.571L10 4.579 8.241 8.142l-3.932.571 2.846 2.774-.672 3.916L10 13.554zm0 2.26L3.827 19.06l1.179-6.875L.01 7.317l6.902-1.003L10 .06l3.087 6.254 6.902 1.003-4.995 4.868 1.18 6.875L10 15.814z"></path>
            </svg> 
        {%endif%}

    </button>
    
    <button class="button" title="Report this post" _="on click toggle .is-active on #report-modal"> 
        <svg xmlns="http://www.w3.org/2000/svg" 
        viewBox="-4 -2 24 24" 
        width="24" 
        fill="#4B7EFF">
        <path d="M2 1h12a2 2 0 0 1 2 2v7a2 2 0 0 1-2 2H2v7a1 1 0 0 1-2 0V1a1 1 0 1 1 2 0z"></path></svg>
    </button>
</div>

aiart_content/templates/imageposts/partials/pagination.html
<nav class="pagination is-centered" role="navigation" aria-label="pagination">
    <ul class="pagination-list">
        {% if page_obj.has_previous %}
            {%if page_obj.previous_page_number != 1 %}
            <li>
                <a href="?page=1&{{ parameters }}" class="pagination-link" aria-label="Goto page 1">1</a>
            </li>
            <li>
                <span class="pagination-ellipsis">&hellip;</span>
            </li>
            {%endif%}
            <li>
                <a href="?page={{ page_obj.previous_page_number }}&{{ parameters }}" class="pagination-link" aria-label="Goto page {{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
            </li>
        {% endif %}      
      
      <li>
        <a class="pagination-link is-current" aria-label="{{ page_obj.number }}" aria-current="page">{{ page_obj.number }}</a>
      </li>

      {% if page_obj.has_next %}
            <li>
                <a href="?page={{ page_obj.next_page_number }}&{{ parameters }}" class="pagination-link" aria-label="Goto page {{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
            </li>
            {%if page_obj.next_page_number != page_obj.paginator.num_pages %}
            <li>
                <span class="pagination-ellipsis">&hellip;</span>
            </li>
            <li>
                <a href="?page={{ page_obj.paginator.num_pages }}&{{ parameters }}" class="pagination-link" aria-label="Goto page {{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
            </li>
            {%endif%}
        {% endif %}
    </ul>
  </nav>

aiart_content/templates/imageposts/partials/post_cards.html
{% load static %}
<ul class="columns is-multiline">
    {% for post in object_list %}
    <div class="column is-2">
        <div class="card">
            <a href="{% url 'content:detail_imagepost' post.uuid %}">
                <div class="card-image">
                    <figure class="image is-4by3">
                        <img src={{post.image_url}} alt="Image" class="post-card-image">
                    </figure>
                </div>
            </a>
            <div class="card-content">
                <div class="content">
                    <div class="block">
                        <p class="post-card-prompt">{{post.positive_prompt}}</p>
                    </div>
                    <hr class="post-card-divider" />
                    <div class="block">
                        <div class="level mb-0 is-mobile">
                            <div class="level-left">
                                <div class="level-item">
                                    <time datetime="{{post.publish_date|date:" Y-m-d"}}">{{post.publish_date|date:"M d, Y"}}</time>
                                </div>                                
                            </div>

                            <div class="level-right">
                                <div class="level-item mr-1">
                                    <strong>{{post.likes}}</strong>
                                </div>
                                <div class="level-item">
                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="-2 -4 24 24" width="24" fill="#BD473F">
                                            <path
                                                d="M9.293 1.55l.707.708.707-.707a5 5 0 1 1 7.071 7.071l-7.07 7.071a1 1 0 0 1-1.415 0L2.222 8.622a5 5 0 1 1 7.07-7.071z">
                                            </path>
                                        </svg>
                                </div>
                                
                                <div class="level-item mr-1 ml-1">
                                    <strong>{{post.views}}</strong>
                                </div>
                                <div class="level-item">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" 
                                    stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-eye">
                                    <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle>
                                    </svg>
                                </div> 
                            </div>
                        </div>
                            <a class="username-field" href="{% url 'auth:profile' post.user.uuid %}">
                                @{{post.user.username}} </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% empty %}
    <li>No posts yet.</li>
    {% endfor %}
</ul>