aiart_auth/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.views import LogoutView

app_name = "auth"
urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name="register"),
    path('profile/<uuid:uuid>', views.ProfileView.as_view(), name="profile"),
    path('profile/', views.ProfileView.as_view(), name="profile"),
    path('profile/edit/',views.ProfileEditView.as_view(), name="profile_edit"),
    path('profile/password/', views.PasswordChange.as_view(), name='password_change')
] 

htmxpatterns = [
   path('follow',views.follow,name="follow"),
]

urlpatterns += htmxpatterns

aiart_content/urls.py
from django.urls import path
from . import views

app_name = 'content'
urlpatterns = [
   path('create/',views.CreateImagePostView, name='create_imagepost'),
   path('detail/<uuid:uuid>', views.DetailImagePostView.as_view(), name='detail_imagepost'),
   path('posts/',views.ListImagePostsView.as_view(), name='list_imagepost'),
   path('followingfeed/',views.ListImagePostsFollowingFeed.as_view(), name='following_feed'),
   path('favorites/',views.ListImagePostsFavorites.as_view(), name='favorites')
]

htmx_urlpatterns = [
   path('like_imagepost/', views.likeImagePost, name="like_imagepost"),
   path('favorite_imagepost/', views.favoriteImagePost, name="favorite_imagepost"),
   path('search/',views.searchView, name='search'),
   path('post_comment',views.postComment,name="post_comment")
]


urlpatterns += htmx_urlpatterns

aiart_main/urls.py
from django.urls import path

from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('help/', views.help, name='help'),
    path('contact/', views.contact, name='contact'),
    path('report/', views.report, name='report'),
]

aiartsharing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('content/', include('aiart_content.urls')),
    path('auth/', include('aiart_auth.urls')),
    path('', include('aiart_main.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aiart_main/models.py
from django.db import models
from aiart_auth.models import CustomUser
from aiart_content.models import ImagePost
from django.utils import timezone
import uuid
# Create your models here.


class Report(models.Model):

    report_choices = [
    ("report_broken_url", "I can't view the image for this post."),
    ("report_not_aiart", "This post is not AI Art."),
    ("report_harassment", "This post is targetted harassment."),
    ("report_selfharm", "This post is promoting suicide or self-harm."),
    ("report_spam", "This post is spam."),
    ("report_untagged_sexual_content", "This post is not tagged for sexual content (18+)."),
    ("report_sexual_content_minors", "This post contains sexual content involving minors."),
    ("report_other", "Other (please use the box below)"),
    ]

    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE) 
    report_date = models.DateTimeField(default=timezone.now, editable=False)
    report_option = models.CharField(max_length=300, choices=report_choices)
    other_option = models.TextField()

class ImagePostReport(Report):
    imagepost = models.ForeignKey(ImagePost, on_delete=models.CASCADE, editable=False)

aiart_main/forms.py
from django import forms
from .models import ImagePostReport
class ImagePostReportForm(forms.ModelForm):

    class Meta:
        model = ImagePostReport
        fields = ("report_option","other_option",)
        labels = {
            "report_option":'Please select an option',
            "other_option":"Explain why you're reporting this post",
        }

aiart_main/views.py
from django.shortcuts import render, HttpResponse
from django.urls import reverse
from aiart_content.forms import SimpleSearchForm, AdvancedLocalSearchForm, AdvancedOnlineServiceSearchForm
from aiart_content.models import ImagePost
from .models import ImagePostReport
# Create your views here.

def index(request):
    simpleform = SimpleSearchForm
    advanced_local_form = AdvancedLocalSearchForm
    advanced_online_form = AdvancedOnlineServiceSearchForm
    totalPosts = ImagePost.objects.count()
    context = {'simpleform':simpleform, 'advanced_local_form':advanced_local_form, 'advanced_online_form': advanced_online_form, 'totalPosts':totalPosts}
    return render(request, template_name='index.html', context=context)

def about(request):
    return render(request, template_name='about.html')

def help(request):
    return render(request, template_name='help.html')

def contact(request):
    return render(request, template_name='contact.html')


#HTMX Views
def report(request):
    if (request.method=='POST'):
        report_option = request.POST['report_option']
        other_option = request.POST['other_option']
        imagepost = ImagePost.objects.get(uuid=request.POST['post_uuid'])
        report = ImagePostReport.objects.create(report_option=report_option,other_option=other_option,user=request.user, imagepost=imagepost)
        report.save()
        return HttpResponse("Report Successful")

aiart_main/templates/partials/footer.html
{%load static %}
<footer class="footer pb-4">
    <div class="content has-text-centered">
      <p>
        <strong>AI ART SHARING</strong> by <a href="https://github.com/bernasx">Bernardo Ribeiro</a>. The source code is licensed
        <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content
        is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY NC SA 4.0</a>.
      </p>
      <p>
        Copyright © 2023 AI ART SHARING
      </p>
    <div class="content">
        <a href="" class="ml-2 mr-2">Contact</a>
        <a href="" class="ml-2 mr-2">Privacy</a>
        <a href="" class="ml-2 mr-2">Terms</a>
    </div>
    </div>
  </footer>

aiart_main/templates/partials/navbar.html
{%load static %}
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="{% url 'main:index' %}">
      <img src="{% static 'aiartlogo.png' %}" width="180" height="28" alt='AI Art Sharing Logo'>
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbar-main"
      onclick="document.querySelector('.navbar-menu').classList.toggle('is-active');">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbar-main" class="navbar-menu">
    <div class="navbar-start">

      <a href="{% url 'content:list_imagepost' %}" class="navbar-item has-text-weight-semibold">
        Posts
      </a>

      {%if user.is_authenticated%}

      <a href="{% url 'content:following_feed' %}" class="navbar-item has-text-weight-semibold">
        Following
      </a>

      <a href="{% url 'content:favorites' %}" class="navbar-item has-text-weight-semibold">
        Favorites
      </a>

      {%endif%}

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link has-text-weight-semibold">
          More
        </a>

        <div class="navbar-dropdown">
          <a href="{% url 'main:help' %}" class="navbar-item">
            Help
          </a>
          <a href="{% url 'main:about' %}" class="navbar-item">
            About
          </a>
          <a href="{% url 'main:contact' %}" class="navbar-item">
            Contact
          </a>
        </div>
      </div>

      {%if user.is_authenticated%}
      <div class="navbar-item">
        <a class="button is-primary" href="{% url 'content:create_imagepost' %}">
          <strong>Upload</strong>
        </a>
      </div>
      {%endif %}

      {%if not user.is_authenticated%}
      <div class="navbar-item">
        <a class="button is-primary" href="{% url 'auth:login' %}">
          <strong>Upload</strong>
        </a>
      </div>
      {%endif %}

    </div>

    {%if user.is_authenticated%}
    <div class="navbar-end">
      <div class="navbar-item">
        <a href="{% url 'auth:profile' user.uuid %}"> {{user.email}} </a>
      </div>
      <div class="navbar-item">
        <div class="buttons">

          <a class="button" href="{% url 'auth:logout' %}">
            Log out
          </a>

        </div>
      </div>
    </div>
    {%else%}
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <a class="button is-primary" href="{% url 'auth:register' %}">
            <strong>Sign up</strong>
          </a>
          <a class="button" href="{% url 'auth:login' %}">
            Log in
          </a>
        </div>
      </div>
    </div>
    {%endif%}

  </div>
</nav>