aiart_auth/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.views import LogoutView

app_name = "auth"
urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name="register"),
    path('profile/<uuid:uuid>', views.ProfileView.as_view(), name="profile"),
    path('profile/', views.ProfileView.as_view(), name="profile"),
    path('profile/edit/',views.ProfileEditView.as_view(), name="profile_edit"),
    path('profile/password/', views.PasswordChange.as_view(), name='password_change')
] 

htmxpatterns = [
   path('follow',views.follow,name="follow"),
]

urlpatterns += htmxpatterns

aiart_content/urls.py
from django.urls import path
from . import views

app_name = 'content'
urlpatterns = [
   path('create/',views.CreateImagePostView, name='create_imagepost'),
   path('detail/<uuid:uuid>', views.DetailImagePostView.as_view(), name='detail_imagepost'),
   path('posts/',views.ListImagePostsView.as_view(), name='list_imagepost'),
   path('followingfeed/',views.ListImagePostsFollowingFeed.as_view(), name='following_feed'),
   path('favorites/',views.ListImagePostsFavorites.as_view(), name='favorites')
]

htmx_urlpatterns = [
   path('like_imagepost/', views.likeImagePost, name="like_imagepost"),
   path('favorite_imagepost/', views.favoriteImagePost, name="favorite_imagepost"),
   path('search/',views.searchView, name='search'),
   path('post_comment',views.postComment,name="post_comment")
]


urlpatterns += htmx_urlpatterns

aiartsharing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('content/', include('aiart_content.urls')),
    path('auth/', include('aiart_auth.urls')),
    path('', include('aiart_main.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aiart_auth/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.utils import timezone
from .managers import CustomUserManager
from django.utils import timezone
import os
import uuid

# Create your models here.

class CustomUser(AbstractBaseUser, PermissionsMixin):
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    email = models.EmailField(("email address"), unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)
    username = models.CharField(max_length=24)
    profile_picture = models.ImageField(upload_to='media/pfp/', default='media/pfp/default.png', blank=True)
    profile_picture_last_update = models.DateTimeField(default=timezone.now)
    bio = models.TextField(max_length=250, default="")

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    # Likes and Favorites
    liked_image_posts = models.ManyToManyField('aiart_content.ImagePost', related_name='liked_image_posts')
    favorited_image_posts = models.ManyToManyField('aiart_content.ImagePost', related_name='favorited_image_posts')

    def __str__(self):
        return self.email

    def profilePictureFilename(self):
        return os.path.basename(self.profile_picture.name)

class Followers(models.Model):
    user_being_followed = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='user_being_followed')
    user_following = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='user_following')

aiart_auth/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from django.forms import EmailField,ModelForm
from .models import CustomUser


# Admin Panel stuff
class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ["email",]


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ["username", "email", "profile_picture","bio"]


# Account Creation
class RegisterForm(UserCreationForm):
    
    class Meta:
        model = CustomUser
        fields = ["username", "email", "password1", "password2"]

class LoginForm(AuthenticationForm):
    # Django probably requires the LoginView to be tied into the "username" name for authentication,
    # so we have to work around that and make this an email field, and make the template properly
    # handle the special username case
    username = EmailField(label='Email', required=True)
        

# Account Management

class EditProfileForm(ModelForm):

    class Meta:
        model = CustomUser
        fields = ["username", "email", "profile_picture","bio"]

aiart_content/forms.py
from django import forms
from .models import ImagePost, ImagePostComment

class ImagePostLocalCreationForm(forms.ModelForm):

    post_type = forms.CharField(widget=forms.HiddenInput, initial='local')

    class Meta:
        model = ImagePost
        fields = ("image_url","model",
                  "hypernetwork","positive_prompt","negative_prompt",
                  "notes","generation_details","isOnlineService","onlineService")
        labels = {
            "image_url":'Image URL',
            "model":"Model",
            "hypernetwork": "Hypernetwork",
            "positive_promopt":"Positive Prompt",
            "negative_prompt":"Negative Prompt",
            "notes":"Notes",
            "generation_details": "Generation Details",
        }

class ImagePostOnlineCreationForm(forms.ModelForm):

    post_type = forms.CharField(widget=forms.HiddenInput, initial='online')

    class Meta:
        model = ImagePost
        fields = ("image_url","model",
                  "hypernetwork","positive_prompt","negative_prompt",
                  "notes","generation_details","isOnlineService","onlineService")
        labels = {
            "image_url":'Image URL',
            "model":"Model",
            "hypernetwork": "Hypernetwork",
            "positive_promopt":"Positive Prompt",
            "negative_prompt":"Negative Prompt",
            "notes":"Notes",
            "generation_details": "Generation Details",
            "onlineService": "Online Service"
        }


    def clean(self):
        cd = super(ImagePostOnlineCreationForm, self).clean()

        onlineService = cd.get("onlineService")
        if onlineService == "":
            self.add_error('onlineService', forms.ValidationError('Please select a service!'))     
        return cd
        

class ImagePostChangeForm(forms.ModelForm):

    class Meta:
        model = ImagePost
        fields = ("image_url","model",
                  "hypernetwork","positive_prompt","negative_prompt",
                  "notes","generation_details","onlineService")
        labels = {
            "image_url":'Image URL',
            "model":"Model",
            "hypernetwork": "Hypernetwork",
            "positive_promopt":"Positive Prompt",
            "negative_prompt":"Negative Prompt",
            "notes":"Notes",
            "generation_details": "Generation Details",
            "isOnlineService": "Generated in an Online Service?",
            "onlineService": "Online Service"
        }

#Search

class SimpleSearchForm(forms.Form):
    keyword = forms.CharField(label="Search for anything", max_length=100, required=False)
    search_type = forms.CharField(widget=forms.HiddenInput, initial='simple')
    
    sort_options = [('recent','Recent'),('popular','Popularity'),('views','Views')]
    sort_by = forms.ChoiceField(label="Sort by", choices=sort_options)

class AdvancedLocalSearchForm(forms.Form):
    prompt = forms.CharField(label="Prompt / Search Term", max_length=100, required=False)
    model = forms.CharField(label="Model", max_length=100, required=False)
    keyword = forms.CharField(label="Keywords", max_length=100, required=False)
    search_type = forms.CharField(widget=forms.HiddenInput, initial='advanced_local')

    sort_options = [('recent','Recent'),('popular','Popularity'),('views','Views')]
    sort_by = forms.ChoiceField(label="Sort by", choices=sort_options)

class AdvancedOnlineServiceSearchForm(forms.Form):
    DALL_E = 'DALL-E'
    NOVEL_AI = 'Novel AI'
    MIDJOURNEY = 'Midjourney'

    choices = [('','---------'),(DALL_E,'DALL-E 2'),(NOVEL_AI,'Novel AI'),(MIDJOURNEY,'Midjourney')]

    prompt = forms.CharField(label="Prompt / Search Term", max_length=100, required=False)
    service = forms.ChoiceField(label="Service", choices=choices, required=False)
    keyword = forms.CharField(label="Keywords", max_length=100, required=False)
    search_type = forms.CharField(widget=forms.HiddenInput, initial='advanced_online')

    sort_options = [('recent','Recent'),('popular','Popularity'),('views','Views')]
    sort_by = forms.ChoiceField(label="Sort by", choices=sort_options)

# Comment

class CommentCreationForm(forms.ModelForm):

    class Meta:
        model = ImagePostComment

        fields = ("content",)
        labels = {
            "content":"Comment on this image!",
        }

aiart_auth/views.py
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.contrib.auth.forms import PasswordChangeForm
from django.views.generic.edit import FormView, UpdateView
from django.contrib.auth import logout
from django.views.generic import DetailView
from django.urls import reverse_lazy
from .forms import RegisterForm, LoginForm, EditProfileForm
from .models import *
from aiart_content.models import ImagePost
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.db.models import Count
from django.shortcuts import render
# Create your views here.

class Login(LoginView):
    template_name = 'login.html'
    next_page = reverse_lazy('main:index')
    authentication_form = LoginForm

class RegisterView(FormView):
    form_class = RegisterForm
    template_name = 'register.html'
    success_url = reverse_lazy('auth:login')

    def form_valid(self, form):
        form.save()  # save the user
        return super().form_valid(form)


class ProfileView(DetailView):
    model = CustomUser
    template_name = 'profile/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            user = CustomUser.objects.get(uuid=self.kwargs.get('uuid'))
        except(CustomUser.DoesNotExist):
            user = CustomUser.objects.get(pk=self.request.user.pk)

        post_count = ImagePost.objects.filter(user=user).count()
        #not entirely sure how this works but it returns the total_likes of all posts of a given user
        total_likes = ImagePost.objects.filter(user=user).aggregate(Count('liked_image_posts'))['liked_image_posts__count']
        user_posts = ImagePost.objects.filter(user=user).order_by('-publish_date')[:18]
        context['user_posts'] = user_posts
        context['post_count'] = post_count
        context['total_likes'] = total_likes
        context['user_being_followed'] = user.uuid

        if(Followers.objects.filter(user_being_followed=user,user_following=self.request.user).exists()):
            context['following_user'] = True
        else:
            context['following_user'] = False

        return context

    
    def get_object(self):
        if not self.kwargs.get('uuid'):
            return CustomUser.objects.get(pk=self.request.user.pk)
        return CustomUser.objects.get(uuid=self.kwargs.get('uuid'))
    
@method_decorator(login_required, name='dispatch')
class ProfileEditView(UpdateView):
    model = CustomUser
    template_name = 'profile/edit.html'
    form_class = EditProfileForm
    success_url = reverse_lazy('auth:profile')

    def get_object(self):
        return CustomUser.objects.get(pk=self.request.user.pk)
    
@method_decorator(login_required, name='dispatch')
class PasswordChange(PasswordChangeView):
    model = CustomUser
    template_name = 'profile/password.html'
    form_class = PasswordChangeForm
    success_url = reverse_lazy('auth:login')

    def form_valid(self, form):
        form.save()
        self.request.session.flush()
        logout(self.request)
        return super().form_valid(form)
    

#HTMX Views

def follow(request):
    # the one being followed
    user = CustomUser.objects.get(uuid=request.POST.get('user_followed'))

    if(user == request.user):
        return

    if(Followers.objects.filter(user_being_followed=user,user_following=request.user).exists()):
        Followers.objects.get(user_being_followed=user,user_following=request.user).delete()
        context = {'following_user':False,'user_being_followed':user.uuid}
        return render(request, 'profile/partials/follow.html', context=context)
    else:
        follow = Followers.objects.create(user_being_followed=user,user_following=request.user)
        follow.save()
        context = {'following_user':True,'user_being_followed':user.uuid}
        return render(request, 'profile/partials/follow.html', context=context)

aiart_auth/templates/profile/edit.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
<form method="POST" action="{% url 'auth:profile_edit' %}" autocomplete='off' enctype="multipart/form-data">
    {% csrf_token %}

    <div class="field">

        <label class="label">{{ form.username.label_tag }}</label>
        {{ form.username.errors }}

        <div class="control">
            {% render_field form.username class="input"%}
        </div>

    </div>

    <div class="field">

        <label class="label">{{ form.email.label_tag }}</label>
        {{ form.email.errors }}

        <div class="control">
            {% render_field form.email class="input"%}
        </div>

    </div>

    <div class="field">

        <label class="label">{{ form.bio.label_tag }}</label>
        {{ form.bio.errors }}

        <div class="control">
            {% render_field form.bio class="textarea"%}
        </div>

    </div>

    <div class="field">

        <label class="label">{{ form.profile_picture.label_tag }}</label>
        {{ form.profile_picture.errors }}

        <div class="control">

            <div id="file-js-example" class="file has-name">
                <label class="file-label">
                    <input type="file" name="profile_picture" accept="image/*" class="file-input"
                        id="id_profile_picture">
                    <span class="file-cta">
                        <span class="file-icon">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                fill="none" stroke="#BD473F" stroke-width="2" stroke-linecap="round"
                                stroke-linejoin="round" class="feather feather-upload">
                                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4">
                                </path>
                                <polyline points="17 8 12 3 7 8"></polyline>
                                <line x1="12" y1="3" x2="12" y2="15"></line>
                            </svg>
                        </span>
                        <span class="file-label">
                            Choose a file…
                        </span>
                    </span>
                    <span class="file-name">
                        <a target="_blank" href="{{user.profile_picture.url}} ">{{user.profilePictureFilename}}</a>
                    </span>
                </label>
            </div>
        </div>

    </div>

    <div class="field is-horizontal">
        <div class="field-label fit-label">
            <!-- Left empty for spacing -->
        </div>
        <div class="field-body">
            <div class="field has-text-right">
                <div class="control">
                    <button type="submit" class="button">Edit Profile</button>
                </div>
            </div>
        </div>
    </div>

</form>

<script>
    const fileInput = document.querySelector('#file-js-example input[type=file]');
    fileInput.onchange = () => {
        if (fileInput.files.length > 0) {
            const fileName = document.querySelector('#file-js-example .file-name');
            fileName.textContent = fileInput.files[0].name;
        }
    }
</script>


{% endblock content %}

aiart_auth/templates/profile/password.html
{% extends 'base.html' %}
{%load widget_tweaks%}
{% block content %}
<form method="POST" action="{% url 'auth:password_change' %}" autocomplete='off'>
    {% csrf_token %}

    <div class="field">

        <label class="label">{{ form.old_password.label_tag }}</label>
        {{ form.old_password.errors }}

        <div class="control">
            {% render_field form.old_password class="input"%}
        </div>

    </div>

    <div class="field">

        <label class="label">{{ form.new_password1.label_tag }}</label>
        {{ form.new_password1.errors }}

        <div class="control">
            {% render_field form.new_password1 class="input"%}
        </div>
        
    </div>
    

    <div class="field">

        <label class="label">{{ form.new_password2.label_tag }}</label>
        {{ form.new_password2.errors }}

        <div class="control">
            {% render_field form.new_password2 class="input"%}
        </div>
        
    </div>

    {{form.new_password1.help_text}}

    {% comment%}
    Login errors tied to authentication
    {% endcomment%}
    {%for error in form.non_field_errors%}
        {{error}}
    {%endfor%}

    
    
    <div class="field is-horizontal">
        <div class="field-label fit-label">
            <!-- Left empty for spacing -->
        </div>
        <div class="field-body">
            <div class="field has-text-right">
                <div class="control">
                    <button type="submit" class="button">Change Password</button>
                </div>
            </div>
        </div>
    </div>

        
    
</form>
{% endblock content %}

aiart_auth/templates/profile/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/profile.css' %}" type="text/css">
<div class="columns mb-0">

    <div class="column is-one-fifth">
        <figure class="image">
            <img id="profile-picture" src="{{customuser.profile_picture.url}}" alt="Image" alt="Profile Picture">
        </figure> 
    </div>

    <div class="column">
        <div class="content">
            <h1 id="username-text" class="is-size-2">{{customuser.username}}</h1>
            {%if customuser.bio != "" %}
                <div class="box mb-0">
                    <h3 class="is-size-5"> Bio: </h3>
                    <p id="bio-text" >{{customuser.bio}}</p>
                </div>
            {%else%}
            <div class="box mb-0">
                <h3 class="is-size-5"> Bio: </h3>
                <p id="bio-text" >-- This user has not added a biography yet.</p>
            </div>
            {%endif%}

            <div class="level mt-4">
                <div class="level-left">
                    <div class="level-item">
                    </div>
                </div>
                <div class="level-right">
                    {%if customuser.uuid == user.uuid%}
                        <div class="level-item">
                            <a class="button"  href="{% url 'auth:profile_edit' %}" title="Edit Profile">
                                <svg xmlns="http://www.w3.org/2000/svg" 
                                width="24" height="24" viewBox="0 0 24 24" 
                                fill="none" stroke="#FAAB50" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit">
                                <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path>
                                </svg>
                            </a>
                        </div>
                        <div class="level-item">
                            <a class="button"  href="{% url 'auth:password_change' %}" title="Change Password">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#BD473F" 
                                stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-lock"><rect x="3" y="11" width="18" height="11" rx="2" ry="2">
                                </rect><path d="M7 11V7a5 5 0 0 1 10 0v4"></path>
                                </svg>
                            </a>
                        </div>
                    {%else%}
                        {%include 'profile/partials/follow.html'%}
                    {%endif%}
                    
                </div>
            </div>
        </div>
        
    </div>
</div>

<div class="columns">
    <div class="column is-one-fifth">
        <div class="box content">
            <h3 class="is-size-5"> Stats: </h3>
            <p>Uploaded images: <strong>{{post_count}}</strong></p>
            <p>Total likes in uploaded images: <strong>{{total_likes}}</strong></p>
        </div>
    </div>

    <div class="column">
        <h1 class="is-size-2 mb-2">Uploaded images:</h1>
        <div class="columns is-multiline is-mobile">
            {%for post in user_posts%}
                <div class="column is-2">
                    <a href="{% url 'content:detail_imagepost' post.uuid %}">
                        <div class="card-image">
                            <figure class="image is-4by3">
                                <img src={{post.image_url}} alt="Image" class="post-card-image">
                            </figure>
                        </div>
                    </a>
                </div>
            {%endfor%}
        </div>
        
        <form id="simpleform" role="search" method="POST" action="{% url 'content:search' %}" autocomplete='off'>
            {%csrf_token%}
            <input type="hidden" name="search_type" value="by_user" id="id_search_type">
            <input type="hidden" name="user_searched" value="{{customuser.uuid}}" id="id_search_type">
            <input type="hidden" name="sort_by" value="recent" id="id_sortby">
            <button type="submit" class="button">See all posts by&nbsp;<span>@{{customuser.username}}</span> </button>       
        </form>

    </div>
</div>    




{% endblock content %}